// Configuration options for Webpack, A JavaScript Module Bundler

// Node.js modules
const { dirname } = require('path') // Returns directory name of a file path
const path = require('path') // Provides utilities for working with files and directory paths

module.exports = {
    mode: 'development', // specifies the mode webpack is running in
    entry: "./src/index.js", // entry point for webpack build process i.e. file first to be processed by webpack
    output: { // output configuration of webpack build.
        filename: 'main.js', // name of the bundle file generated by webpack
        path: path.resolve(--dirname, 'dist'), // specifies the directory where the bundle files will be saved
        // path.resolve is used to generate the full path to the 'dist' directory 
    },
}